# Generated by Django 3.1.3 on 2022-07-14 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
